$page_path = "c:\Users\azrie\PDenv\UserGithub\codex-scientiae\ingestion\compendia\ph\AL2026\.scratch\page_049.md"
$manifest_path = "c:\Users\azrie\PDenv\UserGithub\codex-scientiae\ingestion\compendia\ph\AL2026\.scratch\manifest_049.md"

$page_lines = Get-Content $page_path -Encoding UTF8
$line41 = $page_lines[41]

$manifest_content = "# Manifest: Page 049`n`n"
$manifest_content += "## REPLACE_TABLES`n"
$manifest_content += "- FILL_ME_IN`n`n"
$manifest_content += "## REPAIR_MATH`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "M ∈ mod k [ P ]`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "\( M \in \operatorname{mod} k[P] \)`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "M ∼ = L n ⊕ N`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "\( M \cong L^n \oplus N \)`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "n ≥ 0`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "\( n \ge 0 \)`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "¯ d M ( L ) : = n`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "\( \bar{d}_M(L) := n \)`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "¯ d M ( L )`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "\( \bar{d}_M(L) \)`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "d M ( L )`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "\( d_M(L) \)`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "L = i ∈ [ m ] L i`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "\( L = \bigoplus_{i \in [m]} L_i \)`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "m ≥ 1`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "\( m \ge 1 \)`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "with each L i indecomposable`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "with each \( L_i \) indecomposable`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "¯ d M ( L ) = min i ∈ [ m ] d M ( L i )`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "\( \bar{d}_M(L) = \min_{i \in [m]} d_M(L_i) \)`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "ζ : Z → P`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "\( \zeta : Z \to P \)`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "with Z a poset`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "with \( Z \) a poset`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "R : mod k [ P ] → mod k [ Z ]`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "\( R : \operatorname{mod} k[P] \to \operatorname{mod} k[Z] \)`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "induced by ζ .`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "induced by \( \zeta \).`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "interval I of P .`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "interval \( I \) of \( P \).`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "If ζ essentially covers I ,`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "If \( \zeta \) essentially covers \( I \),`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "any M ∈ mod A ,`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "any \( M \in \operatorname{mod} A \),`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "Assume that ζ essentially covers I .`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "Assume that \( \zeta \) essentially covers \( I \).`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "g : = g 1 0 g 3 g 2`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "\( g := \left[\begin{smallmatrix} g_1 & 0 \\ g_3 & g_2 \end{smallmatrix}\right] \)`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "in k [ P ]`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "in \( k[P] \)`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "ζ covers g ,`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "\( \zeta \) covers \( g \),`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "say ζ ( g ′ ) = g`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "say \( \zeta(g') = g \)`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "for some g ′ in k [ Z ] .`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "for some \( g' \) in \( k[Z] \).`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "Let g vu (resp. g ′ vu ) be the ( v, u ) -entry of g (resp. g ′ ).`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "Let \( g_{vu} \) (resp. \( g'_{vu} \)) be the \( (v, u) \)-entry of \( g \) (resp. \( g' \)).`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "vu Thus we have M ( g i ) = R ( M )( g ′ i ) for all i = 1 , 2 , 3 . Hence`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "Thus we have \( M(g_i) = R(M)(g'_i) \) for all \( i = 1, 2, 3 \). Hence`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "r : = d M ( V I ) , s : = ¯ d R ( M ) ( R ( V I )) .`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "\( r := d_M(V_I) \), \( s := \bar{d}_{R(M)}(R(V_I)) \).`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "r = s .`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "\( r = s \).`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "M ∼ = V r I ⊕ N`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "\( M \cong V_I^r \oplus N \)`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "mod k [ P ] ,`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "\( \operatorname{mod} k[P] \),`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "R ( M ) ∼ = R ( V I ) r ⊕ R ( N ) .`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "\( R(M) \cong R(V_I)^r \oplus R(N) \).`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "r ≤ s .`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "\( r \le s \).`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "R ( M ) ∼ = R ( V I ) s ⊕ L`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "\( R(M) \cong R(V_I)^s \oplus L \)`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "mod k [ Z ] .`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "\( \operatorname{mod} k[Z] \).`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "M = V I`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "\( M = V_I \)`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "d _ { M } ( V _ { I } ) = \bar { d } _ { R ( M ) } ( R ( V _ { I } ) ) .`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "$$`n"
$manifest_content += "d _ { M } ( V _ { I } ) = \bar { d } _ { R ( M ) } ( R ( V _ { I } ) ) .`n"
$manifest_content += "$$`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "d _ { M } ( V _ { I } ) = \text {rank} \begin{bmatrix} M ( g _ { 1 } ) & 0 \\ M ( g _ { 3 } ) & M ( g _ { 2 } ) \end{bmatrix} - \text {rank} \begin{bmatrix} M ( g _ { 1 } ) & 0 \\ 0 & M ( g _ { 2 } ) \end{bmatrix} ,`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "$$`n"
$manifest_content += "d _ { M } ( V _ { I } ) = \text {rank} \begin{bmatrix} M ( g _ { 1 } ) & 0 \\ M ( g _ { 3 } ) & M ( g _ { 2 } ) \end{bmatrix} - \text {rank} \begin{bmatrix} M ( g _ { 1 } ) & 0 \\ 0 & M ( g _ { 2 } ) \end{bmatrix} ,`n"
$manifest_content += "$$`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "M ( g _ { v u } ) = M ( \zeta ( g _ { v u } ^ { \prime } ) ) = R ( M ) ( g _ { v u } ^ { \prime } ) .`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "$$`n"
$manifest_content += "M ( g _ { v u } ) = M ( \zeta ( g _ { v u } ^ { \prime } ) ) = R ( M ) ( g _ { v u } ^ { \prime } ) .`n"
$manifest_content += "$$`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "d _ { M } ( V _ { I } ) = \text {rank} \left [ \begin{matrix} R ( M ) ( g _ { 1 } ^ { \prime } ) & 0 \\ R ( M ) ( g _ { 3 } ^ { \prime } ) & R ( M ) ( g _ { 2 } ^ { \prime } ) \end{matrix} \right ] - \text {rank} \left [ \begin{matrix} R ( M ) ( g _ { 1 } ^ { \prime } ) & 0 \\ 0 & R ( M ) ( g _ { 2 } ^ { \prime } ) \end{matrix} \right ] .`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "$$`n"
$manifest_content += "d _ { M } ( V _ { I } ) = \text {rank} \left [ \begin{matrix} R ( M ) ( g _ { 1 } ^ { \prime } ) & 0 \\ R ( M ) ( g _ { 3 } ^ { \prime } ) & R ( M ) ( g _ { 2 } ^ { \prime } ) \end{matrix} \right ] - \text {rank} \left [ \begin{matrix} R ( M ) ( g _ { 1 } ^ { \prime } ) & 0 \\ 0 & R ( M ) ( g _ { 2 } ^ { \prime } ) \end{matrix} \right ] .`n"
$manifest_content += "$$`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "d _ { V _ { I } } ( V _ { I } ) = \text {rank} \left [ \begin{matrix} R ( V _ { I } ) ( g _ { 1 } ^ { \prime } ) & 0 \\ R ( V _ { I } ) ( g _ { 3 } ^ { \prime } ) & R ( V _ { I } ) ( g _ { 2 } ^ { \prime } ) \end{matrix} \right ] - \text {rank} \left [ \begin{matrix} R ( V _ { I } ) ( g _ { 1 } ^ { \prime } ) & 0 \\ 0 & R ( V _ { I } ) ( g _ { 2 } ^ { \prime } ) \end{matrix} \right ] .`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "$$`n"
$manifest_content += "d _ { V _ { I } } ( V _ { I } ) = \text {rank} \left [ \begin{matrix} R ( V _ { I } ) ( g _ { 1 } ^ { \prime } ) & 0 \\ R ( V _ { I } ) ( g _ { 3 } ^ { \prime } ) & R ( V _ { I } ) ( g _ { 2 } ^ { \prime } ) \end{matrix} \right ] - \text {rank} \left [ \begin{matrix} R ( V _ { I } ) ( g _ { 1 } ^ { \prime } ) & 0 \\ 0 & R ( V _ { I } ) ( g _ { 2 } ^ { \prime } ) \end{matrix} \right ] .`n"
$manifest_content += "$$`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "r = d _ { M } ( V _ { I } ) = s \cdot d _ { V _ { I } } ( V _ { I } ) + \text {rank} \left [ \begin{smallmatrix} L ( g _ { 1 } ^ { \prime } ) & 0 \\ L ( g _ { 3 } ^ { \prime } ) & L ( g _ { 2 } ^ { \prime } ) \end{smallmatrix} \right ] - \text {rank} \left [ \begin{smallmatrix} L ( g _ { 1 } ^ { \prime } ) & 0 \\ 0 & L ( g _ { 2 } ^ { \prime } ) \end{smallmatrix} \right ]`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "$$`n"
$manifest_content += "r = d _ { M } ( V _ { I } ) = s \cdot d _ { V _ { I } } ( V _ { I } ) + \text {rank} \left [ \begin{smallmatrix} L ( g _ { 1 } ^ { \prime } ) & 0 \\ L ( g _ { 3 } ^ { \prime } ) & L ( g _ { 2 } ^ { \prime } ) \end{smallmatrix} \right ] - \text {rank} \left [ \begin{smallmatrix} L ( g _ { 1 } ^ { \prime } ) & 0 \\ 0 & L ( g _ { 2 } ^ { \prime } ) \end{smallmatrix} \right ]`n"
$manifest_content += "$$`n"
$manifest_content += '```' + "`n"
$manifest_content += "`n## REPAIR_PROSE`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "$line41`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "\text {rank} \begin{bmatrix} R ( M ) ( g _ { 1 } ^ { \prime } ) & 0 \\ 0 & R ( M ) ( g _ { 2 } ^ { \prime } ) \end{bmatrix} = s \text {rank} \begin{bmatrix} R ( V _ { I } ) ( g _ { 1 } ^ { \prime } ) & 0 \\ 0 & R ( V _ { I } ) ( g _ { 2 } ^ { \prime } ) \end{bmatrix} + \text {rank} \begin{bmatrix} L ( g _ { 1 } ^ { \prime } ) & 0 \\ 0 & L ( g _ { 2 } ^ { \prime } ) \end{bmatrix} . \tag{4.57}`n"
$manifest_content += '```' + "`n"
$manifest_content += "- RAW: " + '```' + "`n"
$manifest_content += "Note that the formula ( 4.57 ) holds also for M = V I . Thus we have`n"
$manifest_content += '```' + "`n"
$manifest_content += "  FIX: " + '```' + "`n"
$manifest_content += "Note that the formula (4.57) holds also for \( M = V_I \). Thus we have`n"
$manifest_content += '```' + "`n"

Set-Content -Path $manifest_path -Value $manifest_content -Encoding UTF8
