#requires -Version 7.0
<#
  src/toc-engine/toc-engine.ps1 — Single-document and multi-document TOC & Tree Manifest Engine.

  Features:
  - Micro Template Engine (Expand-MdTemplate): zero-dependency 3-pass renderer ({{#each}}, {{#if}}, {{Property}})
  - Model Builder (New-DeliverableTreeModel): SMP surrogate-pair safe interval byte spans [byte_start, byte_end)
  - In-doc contents renderer (Set-MdContentsBlock) & sidecar exporter (Export-MdTreeSidecar)
  - Extensible architecture for future Bibliotheca navigation (compendia, corpora, codices)
#>

$script:TocEngineUtf8 = [System.Text.UTF8Encoding]::new($false)

# GitHub-style heading slug. Owned HERE rather than borrowed from the legacy md-postprocess/md-toc.ps1:
# this module is the TOC engine, and dot-sourcing the module it supersedes made load order decide which
# of two same-named functions won. Anchors written by any lane must match a TOC regenerated by any other,
# so the rule is kept byte-identical to md-toc's: lowercase, drop everything outside [\w\s-], spaces to
# hyphens, trim stray hyphens.
function Get-MdAnchor([string]$h) {
    $a = (($h.ToLowerInvariant() -replace '[^\w\s-]', '') -replace '\s+', '-').Trim('-')
    if ($a -eq '') { return "section-$($h.GetHashCode().ToString('x8'))" }
    return $a
}

# Attribute a supplied index object to the section whose span contains it. This is the ONLY thing the
# engine does with an index: span containment is span arithmetic, which is the engine's whole business.
# What counts as an indexable object — theorem, lemma, definition — is domain knowledge and stays with
# the lane that produced the document.
function Add-IndexSectionAttribution($Index, $Sections, [string]$Slug) {
    $out = [System.Collections.Generic.List[object]]::new()
    foreach ($e in @($Index)) {
        if ($null -eq $e) { continue }
        $off = if ($null -ne $e.byte_start) { [int]$e.byte_start } else { -1 }
        $owner = $null
        if ($off -ge 0) {
            foreach ($s in $Sections) { if ($off -ge $s.byte_start -and $off -lt $s.byte_end) { $owner = $s; break } }
        }
        $out.Add([pscustomobject]@{
                kind          = [string]$e.kind
                class         = [string]$e.class
                number        = [string]$e.number
                label         = [string]$e.label
                identity      = [string]$e.identity
                byte_start    = $off
                anchor        = if ($owner) { $owner.anchor } else { '' }
                section       = if ($owner) { $owner.title } else { '' }
                # link into the MANUSCRIPT — a bare '#anchor' in a sidecar resolves against the sidecar
                relative_link = if ($owner) { $owner.relative_link } else { "$Slug.md" }
            })
    }
    return , $out
}

# Helper: Resolve property path over object scope
function Resolve-TemplateValue($Scope, [string]$Path) {
    if ($null -eq $Scope -or [string]::IsNullOrWhiteSpace($Path)) { return $null }
    $parts = $Path.Split('.')
    $curr = $Scope
    foreach ($p in $parts) {
        if ($null -eq $curr) { return $null }
        if ($curr -is [hashtable] -or $curr -is [System.Collections.IDictionary]) {
            $curr = $curr[$p]
        }
        elseif ($curr.PSObject.Properties[$p]) {
            $curr = $curr.PSObject.Properties[$p].Value
        }
        else {
            return $null
        }
    }
    return $curr
}

# Template scope expansion helper (if & scalar substitution)
function Expand-MdTemplateScope([string]$Text, [object]$Scope, [object]$RootModel) {
    if ([string]::IsNullOrWhiteSpace($Text)) { return $Text }

    # 1. Conditionals: {{#if Property}} ... {{/if}}
    $rxIf = [regex]::new('(?s)\{\{#if\s+([A-Za-z0-9_.]+)\}\}(.*?)(?:\{\{#else\}\}(.*?))?\{\{/if\}\}')
    $Text = $rxIf.Replace($Text, {
        param($match)
        $propPath = $match.Groups[1].Value
        $trueBody = $match.Groups[2].Value
        $falseBody = if ($match.Groups.Count -gt 3) { $match.Groups[3].Value } else { '' }
        $val = Resolve-TemplateValue $Scope $propPath
        if ($null -eq $val) { $val = Resolve-TemplateValue $RootModel $propPath }
        $isTrue = if ($val -is [bool]) { $val } else { -not [string]::IsNullOrWhiteSpace([string]$val) -and $val -ne 0 }
        if ($isTrue) { return Expand-MdTemplateScope $trueBody $Scope $RootModel }
        else { return Expand-MdTemplateScope $falseBody $Scope $RootModel }
    })

    # 2. Scalars: {{Property}}
    $rxVal = [regex]::new('\{\{([A-Za-z0-9_.]+)\}\}')
    $Text = $rxVal.Replace($Text, {
        param($match)
        $propPath = $match.Groups[1].Value
        $val = Resolve-TemplateValue $Scope $propPath
        if ($null -eq $val) { $val = Resolve-TemplateValue $RootModel $propPath }
        if ($null -ne $val) { return [string]$val }
        return ''
    })

    return $Text
}

# Zero-dependency Handlebars-lite micro template expander
function Expand-MdTemplate {
    param(
        [Parameter(Mandatory)][string]$TemplateText,
        [Parameter(Mandatory)][object]$Model
    )
    if ([string]::IsNullOrWhiteSpace($TemplateText)) { return $TemplateText }

    # Pass 1: {{#each Collection}} ... {{/each}}
    # The trailing \r?\n consumes the newline ENDING the {{/each}} tag line, for the same reason the body's
    # leading newline is stripped below: a standalone block tag occupies a line but contributes no output,
    # so leaving its newline behind adds a blank line after every rendered block.
    $rxEach = [regex]::new('(?s)\{\{#each\s+([A-Za-z0-9_.]+)\}\}(.*?)\{\{/each\}\}\r?\n?')
    $expanded = $rxEach.Replace($TemplateText, {
        param($match)
        $propPath = $match.Groups[1].Value
        $body = $match.Groups[2].Value
        # A standalone {{#each}} tag line contributes no output of its own, so the newline that ENDS
        # that tag line is not part of the row body. Without this the body carries a leading newline
        # into every iteration and the rendered list comes out loose — a blank line between each row.
        $body = [regex]::Replace($body, '^\r?\n', '')
        $items = Resolve-TemplateValue $Model $propPath
        if (-not $items) { return '' }
        $sb = [System.Text.StringBuilder]::new()
        foreach ($item in @($items)) {
            $itemExpanded = Expand-MdTemplateScope $body $item $Model
            [void]$sb.Append($itemExpanded)
        }
        return $sb.ToString()
    })

    # Pass 2: {{#if}} and {{Scalar}} at root model level
    return (Expand-MdTemplateScope $expanded $Model $Model)
}

# Assembles the deliverable tree model from Markdown text + metadata
function New-DeliverableTreeModel {
    param(
        [Parameter(Mandatory)][string]$MarkdownText,
        [Parameter(Mandatory)][string]$Slug,
        [hashtable]$Metadata = @{},
        [string]$SourcePath = '',
        # Subject-index objects supplied by the producing lane: { kind; class; number; label; identity;
        # byte_start }. Section attribution is added here; everything else is the lane's to decide.
        [object[]]$Index = @()
    )
    $bytes = $script:TocEngineUtf8.GetBytes($MarkdownText)
    $totalBytes = $bytes.Length

    # Extract H1 title if not provided
    $title = if ($Metadata.ContainsKey('title') -and $Metadata['title']) { [string]$Metadata['title'] }
             elseif ($MarkdownText -match '(?m)^#\s+(.*\S)') { $matches[1].Trim() }
             else { $Slug }

    $authors = if ($Metadata.ContainsKey('authors')) { [string]$Metadata['authors'] } else { '' }
    $doi = if ($Metadata.ContainsKey('doi')) { [string]$Metadata['doi'] } else { '' }

    # Line-by-line scanning while skipping code fences
    $lines = $MarkdownText -split "`n"
    $inFence = $false
    $rawHeadings = [System.Collections.Generic.List[object]]::new()
    $byteOffset = 0

    for ($i = 0; $i -lt $lines.Count; $i++) {
        $ln = $lines[$i]
        $lineByteLen = $script:TocEngineUtf8.GetByteCount($ln) + 1  # +1 for \n

        if ($ln -match '^```') {
            $inFence = -not $inFence
            $byteOffset += $lineByteLen
            continue
        }
        if ($inFence) {
            $byteOffset += $lineByteLen
            continue
        }

        if ($ln -match '^(#{2,6})\s+(.*\S)\s*$') {
            $level = $matches[1].Length
            $text = $matches[2].Trim()

            # Self-referential TOC heading exclusion rule
            if ($text -notmatch '^(?i)(contents|table of contents)$') {
                $anchor = Get-MdAnchor $text
                $rawHeadings.Add([pscustomobject]@{
                    level      = $level
                    title      = $text
                    anchor     = $anchor
                    byte_start = $byteOffset
                })
            }
        }
        $byteOffset += $lineByteLen
    }

    # Compute section intervals [byte_start, byte_end) and character counts
    $sections = [System.Collections.Generic.List[object]]::new()
    for ($i = 0; $i -lt $rawHeadings.Count; $i++) {
        $curr = $rawHeadings[$i]
        $nextStart = if ($i + 1 -lt $rawHeadings.Count) { $rawHeadings[$i + 1].byte_start } else { $totalBytes }

        # No codepoint re-alignment here. The masks helpers index UTF-16 CHAR positions, and these are
        # BYTE offsets — feeding one to the other is a units error that can only ever fire by accident,
        # shifting a boundary by a byte. It also cannot be needed: a heading offset is a line start and
        # byte_end is the next heading's start, so both are codepoint boundaries by construction.
        $bStart = $curr.byte_start
        $bEnd = $nextStart
        $bWidth = [Math]::Max(0, $bEnd - $bStart)
        $indentSpaces = '  ' * ([Math]::Max(0, [int]$curr.level - 2))

        # char_count is deliberately absent: post-register canonicalization drives math to ASCII, so it
        # tracks byte_width to within a fraction of a percent and decides nothing byte_width does not.
        $sections.Add([pscustomobject]@{
            level         = $curr.level
            level_tag     = "H$($curr.level)"
            title         = $curr.title
            anchor        = $curr.anchor
            byte_start    = $bStart
            byte_end      = $bEnd
            byte_width    = $bWidth
            indent        = $indentSpaces
            relative_link = "$Slug.md#$($curr.anchor)"
        })
    }

    # --- subject index: SUPPLIED by the lane, attributed here ---------------------------------------
    # The engine renders an index; it does not discover one. What counts as a numbered, citable object
    # is domain knowledge — it arrives from the converter that knows it emitted a theorem, never from
    # pattern-matching the rendered markdown. A lane with no object evidence supplies nothing and the
    # manifest honestly carries no index, which keeps the capability gap visible.
    #
    # It rides in the MANIFEST rather than a sidecar deliberately: the manifest is read up front, so the
    # inventory is in context BEFORE the manuscript is — the one thing a cross-reference lookup cannot
    # give you, since by the time you hit "by theorem 2.9" attention already holds the document.
    $index = Add-IndexSectionAttribution $Index $sections $Slug

    $header = [pscustomobject]@{
        slug          = $Slug
        title         = $title
        authors       = $authors
        doi           = $doi
        total_bytes   = $totalBytes
        section_count = $sections.Count
        index_count   = $index.Count
        source_file   = "$Slug.md"
        # RELATIVE, always. The manifest ships inside the bundle beside the document it indexes, so an
        # absolute path is a dead link for every reader but the machine that generated it — and it leaks
        # that machine's directory layout into a publishable artifact.
        source_path   = "$Slug.md"
        generated_at  = [System.DateTime]::UtcNow.ToString('o')
    }

    return [pscustomobject]@{
        Header   = $header
        Sections = $sections
        Index    = $index
    }
}

# Refresh or insert in-doc ## Contents block in Markdown text
function Set-MdContentsBlock {
    param(
        [Parameter(Mandatory)][string]$MarkdownText,
        [string]$Slug = 'doc',
        [string]$TemplatePath = (Join-Path $PSScriptRoot 'templates/in-doc-contents.template.md')
    )
    if ([string]::IsNullOrWhiteSpace($MarkdownText)) { return $MarkdownText }
    $model = New-DeliverableTreeModel -MarkdownText $MarkdownText -Slug $Slug
    if ($model.Sections.Count -eq 0) { return $MarkdownText }

    $templateText = [System.IO.File]::ReadAllText($TemplatePath, $script:TocEngineUtf8)
    # ONE trailing newline, not two: the block is spliced in as LINES, so each trailing empty element
    # becomes another newline when the document is rejoined. "`n`n" here yields a triple break before
    # the first body heading.
    $blockText = (Expand-MdTemplate -TemplateText $templateText -Model $model).TrimEnd() + "`n"

    # Replace existing ## Contents block or insert before first H2
    $lines = [System.Collections.Generic.List[string]]::new([string[]]($MarkdownText -split "`n"))
    $inFence = $false; $start = -1; $end = -1; $firstH2 = -1
    for ($i = 0; $i -lt $lines.Count; $i++) {
        $ln = $lines[$i]
        if ($ln -match '^```') { $inFence = -not $inFence; continue }
        if ($inFence) { continue }
        if ($ln -match '^##\s+Contents\s*$') { if ($start -lt 0) { $start = $i }; continue }
        if ($ln -match '^##\s') {
            if ($start -ge 0 -and $end -lt 0) { $end = $i }
            if ($firstH2 -lt 0) { $firstH2 = $i }
        }
    }

    $blockLines = $blockText -split "`n"
    if ($start -ge 0) {
        $stop = if ($end -ge 0) { $end } else { $lines.Count }
        $lines.RemoveRange($start, $stop - $start)
        $lines.InsertRange($start, $blockLines)
    }
    elseif ($firstH2 -ge 0) {
        $lines.InsertRange($firstH2, $blockLines)
    }
    else { return $MarkdownText }

    return ($lines -join "`n")
}

# Payload inventory: everything that ships in this bundle, as preformatted labels (the template engine's
# conditionals are too thin to format sizes inline). Enumerated from the output dir; the two sidecars
# this pass is about to write do not exist on disk yet, so they are appended explicitly. A manifest that
# presents itself as the bundle entrypoint has to name the payload it is an entrypoint TO — assets and
# the machine sidecar are otherwise invisible to a reader holding only the tree.
function Get-MdPayloadInventory {
    param(
        [Parameter(Mandatory)][string]$OutDir,
        [Parameter(Mandatory)][string]$Slug,
        [switch]$NoTree,
        [switch]$NoJsonl
    )
    $items = [System.Collections.Generic.List[object]]::new()
    $treeName = "$Slug-tree.md"
    $jsonlName = "$Slug.toc.jsonl"
    if (Test-Path -LiteralPath $OutDir -PathType Container) {
        $root = [System.IO.Path]::GetFullPath($OutDir)
        foreach ($f in @(Get-ChildItem -LiteralPath $OutDir -File -Recurse | Sort-Object FullName)) {
            $rel = [System.IO.Path]::GetRelativePath($root, $f.FullName).Replace('\', '/')
            if ($rel -eq $treeName -or $rel -eq $jsonlName) { continue }
            $items.Add([pscustomobject]@{ label = "$rel ($($f.Length) B)" })
        }
    }
    if (-not $NoTree) { $items.Add([pscustomobject]@{ label = $treeName }) }
    if (-not $NoJsonl) { $items.Add([pscustomobject]@{ label = $jsonlName }) }
    return , $items
}

# Export standalone Tree Manifest sidecar files ({slug}-tree.md and {slug}.toc.jsonl)
function Export-MdTreeSidecar {
    param(
        [Parameter(Mandatory)][string]$MarkdownPath,
        [Parameter(Mandatory)][string]$OutDir,
        [string]$TemplatePath = (Join-Path $PSScriptRoot 'templates/single-doc-tree.template.md'),
        [string]$Slug = '',
        [hashtable]$Metadata = @{},
        [object[]]$Index = @(),
        [switch]$DisableTreeToc,
        [switch]$DisableJsonlToc
    )
    if (-not (Test-Path -LiteralPath $MarkdownPath -PathType Leaf)) { return $null }
    New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
    $srcPath = (Resolve-Path -LiteralPath $MarkdownPath).Path
    $fileName = Split-Path -Leaf $srcPath

    if ([string]::IsNullOrWhiteSpace($Slug)) {
        $Slug = $fileName -replace '(-latex)?\.md$', ''
    }

    $text = [System.IO.File]::ReadAllText($srcPath, $script:TocEngineUtf8)
    $model = New-DeliverableTreeModel -MarkdownText $text -Slug $Slug -Metadata $Metadata -SourcePath $srcPath -Index $Index
    $model | Add-Member -NotePropertyName Payload -NotePropertyValue (
        Get-MdPayloadInventory -OutDir $OutDir -Slug $Slug -NoTree:$DisableTreeToc -NoJsonl:$DisableJsonlToc) -Force

    $tocMdPath = $null
    if (-not $DisableTreeToc) {
        $templateText = [System.IO.File]::ReadAllText($TemplatePath, $script:TocEngineUtf8)
        $sidecarText = Expand-MdTemplate -TemplateText $templateText -Model $model
        $tocMdPath = Join-Path $OutDir "$Slug-tree.md"
        [System.IO.File]::WriteAllText($tocMdPath, $sidecarText, $script:TocEngineUtf8)
    }

    $tocJsonlPath = $null
    if (-not $DisableJsonlToc) {
        # Two record types in one sidecar, discriminated by `record`: the bundle surface stays small and a
        # consumer streams one file. Section rows keep their shape; object rows carry the TYPED index —
        # kind and class as fields rather than words inside a label, which is what makes them queryable.
        $jsonlLines = [System.Collections.Generic.List[string]]::new()
        foreach ($s in $model.Sections) {
            $jsonlLines.Add(([pscustomobject]@{
                        record        = 'section'
                        level         = $s.level
                        heading       = $s.title
                        anchor        = $s.anchor
                        byte_start    = $s.byte_start
                        byte_end      = $s.byte_end
                        byte_width    = $s.byte_width
                        relative_link = $s.relative_link
                    } | ConvertTo-Json -Compress))
        }
        foreach ($e in $model.Index) {
            $jsonlLines.Add(([pscustomobject]@{
                        record        = 'object'
                        kind          = $e.kind
                        class         = $e.class
                        number        = $e.number
                        label         = $e.label
                        identity      = $e.identity
                        anchor        = $e.anchor
                        byte_start    = $e.byte_start
                        relative_link = $e.relative_link
                    } | ConvertTo-Json -Compress))
        }
        $tocJsonlPath = Join-Path $OutDir "$Slug.toc.jsonl"
        [System.IO.File]::WriteAllText($tocJsonlPath, ($jsonlLines -join "`n") + "`n", $script:TocEngineUtf8)
    }

    return [pscustomobject]@{
        toc_md    = $tocMdPath
        toc_jsonl = $tocJsonlPath
        entries   = $model.Sections.Count
    }
}
