#requires -Version 7.0
<#
  src/md-postprocess/md-anchor.ps1 — THE heading-slug engine. One definition, repo-wide.

  This is a cross-cutting invariant, not a convenience: finalize (chunk-stream emission), md-repair
  (post-hoc TOC regeneration), toc-engine (sidecars + in-doc contents) and the latex lane must all
  produce the SAME slug for the same heading. An anchor written by one lane is resolved by a TOC
  regenerated by another, so two implementations that agree today and drift tomorrow break links
  silently — the failure shows up as a dead anchor in a shipped document, far from the edit.

  It lived in md-postprocess/md-toc.ps1 and was COPIED into toc-engine when that module was made
  independent of the legacy one. Two live copies of an invariant is the drift waiting to happen, so it
  moves here — the shared tier, beside masks/jsonl/runs — and both consume it.

  GitHub-style: lowercase, drop everything outside [\w\s-], spaces to hyphens, trim stray hyphens.
  A heading that slugs to nothing (pure punctuation) gets a stable content-derived fallback rather than
  an empty anchor, so the link still resolves and duplicates still differ.
#>

function Get-MdAnchor([string]$h) {
    $a = (($h.ToLowerInvariant() -replace '[^\w\s-]', '') -replace '\s+', '-').Trim('-')
    if ($a -eq '') { return "section-$($h.GetHashCode().ToString('x8'))" }
    return $a
}
