#requires -Version 7.0
<#
  src/audits/md-toc.ps1 — heading anchors, `## Contents` blocks, and standalone byte-spanned TOC sidecars.

  THE one slug engine: finalize (chunk-stream emission), md-repair (post-hoc regeneration), and
  latex-ingest (born-complete deliverable) all link through Get-MdAnchor, so an anchor written by
  any lane matches a TOC regenerated by any other.

  Conventions carried:
  - GitHub-style slugs; hierarchical indentation at 2 spaces PER heading level below H2 (H2 flush, H3 one indent, ...)
  - Post-processing Tree Manifest TOC Sidecar (`{slug}-tree.md`): Single-document payload entrypoint combining
    YAML frontmatter metadata, payload file inventory, LLM navigation instructions, and a hierarchical Markdown tree
    with relative links `[Section](path/to/paper.md#anchor)` and byte spans (`[byte_start..byte_end)`, `bytes`, `tokens_est`).
#>

$script:TocUtf8 = [System.Text.UTF8Encoding]::new($false)

# GitHub-style heading slug
function Get-MdAnchor([string]$h) {
    $a = (($h.ToLowerInvariant() -replace '[^\w\s-]', '') -replace '\s+', '-').Trim('-')
    if ($a -eq '') { return "section-$($h.GetHashCode().ToString('x8'))" }
    return $a
}

# Fence-aware H2+ heading scan over markdown TEXT -> { level; text } in reading order
function Get-MdContentsEntries([string]$Markdown) {
    $entries = [System.Collections.Generic.List[object]]::new()
    $inFence = $false
    foreach ($ln in ($Markdown -split "`n")) {
        if ($ln -match '^```') { $inFence = -not $inFence; continue }
        if ($inFence) { continue }
        if ($ln -match '^(#{2,6})\s+(.*\S)\s*$') {
            $text = $matches[2]
            if ($text -match '^(?i)contents$') { continue }
            $entries.Add([pscustomobject]@{ level = $matches[1].Length; text = $text })
        }
    }
    return ,$entries
}

# Build the block from entries. Indentation is hierarchical: 2 spaces per level below H2
function New-MdContentsBlock($Entries) {
    if (-not $Entries -or @($Entries).Count -eq 0) { return $null }
    $toc = foreach ($e in $Entries) { ('  ' * ([Math]::Max(0, [int]$e.level - 2))) + "- [$($e.text)](#$(Get-MdAnchor $e.text))" }
    return "## Contents`n`n" + ($toc -join "`n") + "`n"
}

# Insert or refresh the block IN TEXT. An existing `## Contents` section is replaced in place.
function Set-MdContentsBlock([string]$Markdown) {
    if ([string]::IsNullOrWhiteSpace($Markdown)) { return $Markdown }
    $entries = Get-MdContentsEntries $Markdown
    if ($entries.Count -eq 0) { return $Markdown }
    $blockLines = [string[]](@((New-MdContentsBlock $entries).TrimEnd() -split "`n") + @(''))

    $lines = [System.Collections.Generic.List[string]]::new([string[]]($Markdown -split "`n"))
    $inFence = $false; $start = -1; $end = -1; $firstH2 = -1
    for ($i = 0; $i -lt $lines.Count; $i++) {
        $ln = $lines[$i]
        if ($ln -match '^```') { $inFence = -not $inFence; continue }
        if ($inFence) { continue }
        if ($ln -match '^##\s+Contents\s*$') { if ($start -lt 0) { $start = $i }; continue }
        if ($ln -match '^##\s') {
            if ($start -ge 0 -and $end -lt 0) { $end = $i }
            if ($firstH2 -lt 0) { $firstH2 = $i }
        }
    }
    if ($start -ge 0) {
        $stop = if ($end -ge 0) { $end } else { $lines.Count }
        $lines.RemoveRange($start, $stop - $start)
        $lines.InsertRange($start, $blockLines)
    }
    elseif ($firstH2 -ge 0) {
        $lines.InsertRange($firstH2, $blockLines)
    }
    else { return $Markdown }
    return ($lines -join "`n")
}

# Line index over raw file bytes for exact byte-span calculation
function Get-MdLineIndexFromBytes([byte[]]$Bytes) {
    $lines = [System.Collections.Generic.List[object]]::new()
    $n = $Bytes.Length
    $start = 0; $lineNo = 1
    for ($i = 0; $i -lt $n; $i++) {
        if ($Bytes[$i] -eq 0x0A) {
            $contentEnd = $i
            if ($contentEnd -gt $start -and $Bytes[$contentEnd - 1] -eq 0x0D) { $contentEnd-- }
            $len = $contentEnd - $start
            $text = if ($len -gt 0) { $script:TocUtf8.GetString($Bytes, $start, $len) } else { '' }
            $lines.Add([pscustomobject]@{ Line = $lineNo; Offset = $start; Length = $len; Text = $text })
            $lineNo++; $start = $i + 1
        }
    }
    if ($start -lt $n) {
        $contentEnd = $n
        if ($contentEnd -gt $start -and $Bytes[$contentEnd - 1] -eq 0x0D) { $contentEnd-- }
        $len = $contentEnd - $start
        $lines.Add([pscustomobject]@{ Line = $lineNo; Offset = $start; Length = $len; Text = $script:TocUtf8.GetString($Bytes, $start, $len) })
    }
    return $lines
}

# Extract H2+ headings with exact on-disk byte spans [byte_start, byte_end) over a Markdown file
function Get-MdByteSpannedEntries([string]$MarkdownPath) {
    if (-not (Test-Path -LiteralPath $MarkdownPath -PathType Leaf)) { return @() }
    $bytes = [System.IO.File]::ReadAllBytes($MarkdownPath)
    $lineIdx = Get-MdLineIndexFromBytes $bytes
    $entries = [System.Collections.Generic.List[object]]::new()
    $inFence = $false

    foreach ($l in $lineIdx) {
        $ln = $l.Text
        if ($ln -match '^```') { $inFence = -not $inFence; continue }
        if ($inFence) { continue }
        if ($ln -match '^(#{2,6})\s+(.*\S)\s*$') {
            $text = $matches[2]
            if ($text -match '^(?i)contents$') { continue }
            $entries.Add([pscustomobject]@{
                level      = $matches[1].Length
                text       = $text
                anchor     = Get-MdAnchor $text
                byte_start = $l.Offset
                byte_end   = $bytes.Length
                bytes      = 0
                tokens_est = 0
            })
        }
    }

    # Compute section byte spans [byte_start, byte_end) and byte sizes
    for ($i = 0; $i -lt $entries.Count; $i++) {
        $curr = $entries[$i]
        $nextOffset = if ($i + 1 -lt $entries.Count) { $entries[$i + 1].byte_start } else { $bytes.Length }
        $curr.byte_end = $nextOffset
        $curr.bytes = [Math]::Max(0, $nextOffset - $curr.byte_start)
        $curr.tokens_est = [Math]::Max(1, [int][Math]::Round($curr.bytes / 4.0))
    }

    return ,$entries
}

# Build a single-document Tree Manifest TOC sidecar combining frontmatter, payload inventory, agent instructions, and byte-spanned markdown tree links
function New-MdTocSidecar {
    param(
        [Parameter(Mandatory)] [string]$MarkdownPath,
        [string]$Title = '',
        [string]$Slug = ''
    )
    if (-not (Test-Path -LiteralPath $MarkdownPath -PathType Leaf)) { return $null }
    $srcPath = (Resolve-Path -LiteralPath $MarkdownPath).Path
    $srcDir  = Split-Path -Parent $srcPath
    $bytes = [System.IO.File]::ReadAllBytes($srcPath)
    $text = $script:TocUtf8.GetString($bytes)
    $fileName = Split-Path -Leaf $srcPath

    if ([string]::IsNullOrWhiteSpace($Slug)) {
        $Slug = $fileName -replace '(-latex)?\.md$', ''
    }

    if ([string]::IsNullOrWhiteSpace($Title)) {
        if ($text -match '(?m)^#\s+(.*\S)') { $Title = $matches[1].Trim() }
        else { $Title = $Slug }
    }

    $entries = Get-MdByteSpannedEntries $srcPath
    $totalBytes = $bytes.Length
    $totalTokensEst = [Math]::Max(1, [int][Math]::Round($totalBytes / 4.0))
    $nowIso = [System.DateTime]::UtcNow.ToString('o')

    # Frontmatter metadata
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine("---")
    [void]$sb.AppendLine("title: `"$Title`"")
    [void]$sb.AppendLine("slug: `"$Slug`"")
    [void]$sb.AppendLine("source_file: `"$fileName`"")
    [void]$sb.AppendLine("file_bytes: $totalBytes")
    [void]$sb.AppendLine("total_tokens_est: $totalTokensEst")
    [void]$sb.AppendLine("generated_at: `"$nowIso`"")
    [void]$sb.AppendLine("---")
    [void]$sb.AppendLine()

    # Title & Payload Header
    [void]$sb.AppendLine("# Tree Manifest & TOC Entrypoint: ``$Slug``")
    [void]$sb.AppendLine()
    [void]$sb.AppendLine("Document: `"$Title`" | Source: ``$fileName`` | Bytes: $totalBytes | Est. Tokens: ~$totalTokensEst")
    [void]$sb.AppendLine()
    [void]$sb.AppendLine("Payload Files:")
    [void]$sb.AppendLine("- ``./$fileName`` ($totalBytes bytes)")
    [void]$sb.AppendLine("- ``./$Slug-tree.md``")
    
    # Check for local assets folder
    $assetDir = Join-Path $srcDir $Slug
    if (Test-Path -LiteralPath $assetDir -PathType Container) {
        $assetFiles = Get-ChildItem -LiteralPath $assetDir -File
        foreach ($af in $assetFiles) {
            [void]$sb.AppendLine("- ``./$Slug/$($af.Name)`` ($($af.Length) bytes)")
        }
    }
    [void]$sb.AppendLine()

    # Agent Navigation Instructions
    [void]$sb.AppendLine("## Instructions")
    [void]$sb.AppendLine()
    [void]$sb.AppendLine("Treat this deliverable as a byte-addressable manuscript. You can selectively read specific sections using line/byte range lookups (``view_file``) to manage context overload.")
    [void]$sb.AppendLine("Seek to ``[byte_start, byte_end)`` using relative links to inspect any section directly without scanning the entire file.")
    [void]$sb.AppendLine()

    # Contents & Byte-Spanned Tree
    [void]$sb.AppendLine("## Contents & Byte-Spanned Tree")
    [void]$sb.AppendLine()

    if ($entries.Count -gt 0) {
        foreach ($e in $entries) {
            $indent = '  ' * ([Math]::Max(0, [int]$e.level - 2))
            $line = "$indent- [$($e.text)]($fileName#$($e.anchor)) — (bytes $($e.byte_start)..$($e.byte_end), $($e.bytes) bytes, ~$($e.tokens_est) tokens)"
            [void]$sb.AppendLine($line)
        }
    } else {
        [void]$sb.AppendLine("*No section headings detected.*")
    }

    return $sb.ToString()
}

# Export standalone Tree Manifest sidecar files ({slug}-tree.md and {slug}.toc.jsonl)
function Export-MdTocSidecar {
    param(
        [Parameter(Mandatory)] [string]$MarkdownPath,
        [Parameter(Mandatory)] [string]$OutDir,
        [string]$Title = '',
        [string]$Slug = ''
    )
    if (-not (Test-Path -LiteralPath $MarkdownPath -PathType Leaf)) { return $null }
    New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
    $srcPath = (Resolve-Path -LiteralPath $MarkdownPath).Path
    $fileName = Split-Path -Leaf $srcPath

    if ([string]::IsNullOrWhiteSpace($Slug)) {
        $Slug = $fileName -replace '(-latex)?\.md$', ''
    }

    $sidecarText = New-MdTocSidecar -MarkdownPath $srcPath -Title $Title -Slug $Slug
    $tocMdPath = Join-Path $OutDir "$Slug-tree.md"
    [System.IO.File]::WriteAllText($tocMdPath, $sidecarText, $script:TocUtf8)

    # Machine JSONL TOC sidecar ({slug}.toc.jsonl)
    $entries = Get-MdByteSpannedEntries $srcPath
    $jsonlLines = foreach ($e in $entries) {
        [pscustomobject]@{
            level      = $e.level
            heading    = $e.text
            anchor     = $e.anchor
            byte_start = $e.byte_start
            byte_end   = $e.byte_end
            bytes      = $e.bytes
            tokens_est = $e.tokens_est
        } | ConvertTo-Json -Compress
    }
    $tocJsonlPath = Join-Path $OutDir "$Slug.toc.jsonl"
    [System.IO.File]::WriteAllText($tocJsonlPath, ($jsonlLines -join "`n") + "`n", $script:TocUtf8)

    return [pscustomobject]@{
        toc_md    = $tocMdPath
        toc_jsonl = $tocJsonlPath
        entries   = $entries.Count
    }
}
