#!/usr/bin/env python3
"""Read the JSON generated by generate_contents_byte_spans.py and update
CONTENTS.md, replacing the existing "(lines X-Y)" placeholders with the
corresponding "(bytes start-end)" spans.
"""
import json
from pathlib import Path
import re

repo_root = Path(r"D:\aghado01\codex-scientiae")
contents_path = repo_root / "codices" / "Grimmett2006" / "Chapters" / "CONTENTS.md"
json_path = repo_root / ".antigravity" / "helpers" / "contents_byte_spans.json"

# Load JSON entries
with json_path.open('r', encoding='utf-8') as f:
    entries = json.load(f)

# Build a lookup keyed by (chapter, anchor)
lookup = {(e['chapter'], e['anchor']): (e['startByte'], e['endByte']) for e in entries}

# Pattern to find the placeholder "(lines X-Y)" in a line
line_span_pat = re.compile(r"\(lines\s+\d+-\d+\)")

updated_lines = []
with contents_path.open('r', encoding='utf-8') as f:
    for raw_line in f:
        line = raw_line.rstrip('\n')
        if line_span_pat.search(line):
            # Extract chapter file and anchor from the markdown link
            link_match = re.search(r"\(([^)#]+)\.md#([^\)]+)\)", line)
            if link_match:
                raw_file = link_match.group(1).replace('%20', ' ')
                chapter_file = raw_file + '.md'
                anchor_part = link_match.group(2)
                anchor = anchor_part.split('#')[-1]
                key = (chapter_file, anchor)
                if key in lookup:
                    start, end = lookup[key]
                    new_span = f"(bytes {start}-{end})"
                    line = line_span_pat.sub(new_span, line)
        updated_lines.append(line)

# Write back the updated CONTENTS.md
contents_path.write_text('\n'.join(updated_lines) + '\n', encoding='utf-8')
print(f"Updated {contents_path} with byte spans.")
