# PowerShell script to generate a structured JSON file with byte offset spans for each TOC entry in CONTENTS.md
# Output JSON will be written to .antigravity/helpers/contents_byte_spans.json

$repoRoot   = "C:\Users\azrie\PDenv\UserGithub\codex-scientiae"
$contentsPath = Join-Path $repoRoot "codices\Grimmett2006\Chapters\CONTENTS.md"
$chapterDir   = Join-Path $repoRoot "codices\Grimmett2006\Chapters"
$outputPath   = Join-Path $repoRoot ".antigravity\helpers\contents_byte_spans.json"

# ------------------------------------------------------------
# Build a map: ChapterFile -> AnchorID -> StartByteOffset
# ------------------------------------------------------------
$anchorMap = @{}
Get-ChildItem $chapterDir -Filter "Chapter??*.md" | ForEach-Object {
    $fileName = $_.Name
    $filePath = $_.FullName
    $bytesSoFar = 0
    Get-Content $filePath -Encoding UTF8 | ForEach-Object {
        $line = $_
        # Detect anchor tags like <a id="sec-1-2"> or <a id="ch-1">
        if ($line -match '<a id="([^\"]+)">') {
            $anchor = $Matches[1]
            if (-not $anchorMap.ContainsKey($fileName)) { $anchorMap[$fileName] = @{} }
            $anchorMap[$fileName][$anchor] = $bytesSoFar
        }
        # Include newline in byte count (UTF8 \n)
        $bytesSoFar += [System.Text.Encoding]::UTF8.GetByteCount($line + "`n")
    }
}

function Get-EndOffset($fileName, $anchor) {
    $anchors = $anchorMap[$fileName].Keys | Sort-Object
    $idx = $anchors.IndexOf($anchor)
    if ($idx -lt 0) { return $null }
    if ($idx + 1 -lt $anchors.Count) {
        $next = $anchors[$idx + 1]
        return $anchorMap[$fileName][$next] - 1
    } else {
        $fileInfo = Get-Item (Join-Path $chapterDir $fileName)
        return $fileInfo.Length - 1
    }
}

# ------------------------------------------------------------
# Parse CONTENTS.md lines and collect byte spans
# ------------------------------------------------------------
$entries = @()
Get-Content $contentsPath -Encoding UTF8 | ForEach-Object {
    $rawLine = $_
    # Look for markdown link to a chapter file with an anchor (e.g., (Chapter01.Random-Cluster%20Measures.md#sec-1-1))
    if ($rawLine -match '\\(([^)#]+)\\.md#([^\)]+)\\)') {
        $rawFile   = $Matches[1]   # may contain %20
        $anchorPart = $Matches[2]
        # Decode %20 to spaces for actual file name
        $decodedFile = $rawFile -replace "%20", " "
        $chapterFile = $decodedFile + ".md"
        # If there are multiple "#" in anchorPart, take the last segment as the anchor id
        $anchorSegments = $anchorPart -split "#"
        $anchor = $anchorSegments[-1]
        if ($anchorMap.ContainsKey($chapterFile) -and $anchorMap[$chapterFile].ContainsKey($anchor)) {
            $start = $anchorMap[$chapterFile][$anchor]
            $end   = Get-EndOffset $chapterFile $anchor
            $entry = [ordered]@{
                chapter   = $chapterFile
                anchor    = $anchor
                startByte = $start
                endByte   = $end
                lineText  = $rawLine.Trim()
            }
            $entries += $entry
        }
    }
}

# Write JSON (pretty printed) to the output file
$json = $entries | ConvertTo-Json -Depth 4 -Compress
# Ensure the target directory exists
$targetDir = Split-Path $outputPath -Parent
if (-not (Test-Path $targetDir)) { New-Item -ItemType Directory -Path $targetDir | Out-Null }
Set-Content -Path $outputPath -Value $json -Encoding UTF8
Write-Host "Generated byte‑span JSON at $outputPath"
