#requires -Version 7.0

BeforeAll {
    $script:RepositoryRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../..'))
    $script:RecipeRoot = Join-Path $script:RepositoryRoot 'brewery/uv'
    $script:Pin = Get-Content -LiteralPath (Join-Path $script:RecipeRoot 'pin.json') -Raw |
        ConvertFrom-Json -AsHashtable
    $script:PackageUv = Join-Path $script:RepositoryRoot 'packages/uv/uv.exe'
}

Describe 'pinned uv and Python toolchain' {
    It 'keeps the bootstrap, Python selector, project requirement, lock, and export consistent' {
        $script:Pin.schema | Should -BeExactly 'codex-scientiae/toolchain-pin/1'
        $script:Pin.tool | Should -BeExactly 'uv'
        $script:Pin.version | Should -BeExactly '0.11.23'

        $pythonVersion = (Get-Content -LiteralPath (
                Join-Path $script:RepositoryRoot '.python-version') -Raw).Trim()
        $pythonVersion | Should -BeExactly $script:Pin.python_version

        $pyproject = Get-Content -LiteralPath (
            Join-Path $script:RepositoryRoot 'pyproject.toml') -Raw
        $pyproject | Should -Match (
            '(?m)^required-version\s*=\s*"==' +
            [regex]::Escape($script:Pin.version) + '"\s*$')
        $pyproject | Should -Match '(?ms)^\[dependency-groups\]\s*dev\s*=\s*\[.*?"pytest'
        $buildSection = [regex]::Match(
            $pyproject, '(?ms)^\[build-system\]\s*(?<body>.*?)(?=^\[)').Groups['body'].Value
        $developmentSection = [regex]::Match(
            $pyproject, '(?ms)^\[dependency-groups\]\s*(?<body>.*?)(?=^\[)').Groups['body'].Value
        foreach ($buildPin in @('editables==0.6', 'hatchling==1.32.0')) {
            $buildSection | Should -Match ([regex]::Escape($buildPin))
            $developmentSection | Should -Match ([regex]::Escape($buildPin))
        }

        Test-Path -LiteralPath (Join-Path $script:RepositoryRoot 'uv.lock') -PathType Leaf |
            Should -BeTrue
        $requirements = Get-Content -LiteralPath (
            Join-Path $script:RepositoryRoot 'requirements.txt') -Raw
        $requirements | Should -Match '(?m)^# This file was autogenerated by uv'
        $requirements | Should -Not -Match '(?m)^pytest=='

        $script:Pin.artifacts.Keys | Sort-Object | Should -Be @(
            'windows-arm64', 'windows-x64')
        foreach ($artifact in $script:Pin.artifacts.Values) {
            $artifact.url | Should -Match (
                '^https://github\.com/astral-sh/uv/releases/download/' +
                [regex]::Escape($script:Pin.version) + '/')
            $artifact.sha256 | Should -Match '^[0-9a-f]{64}$'
        }
    }

    It 'uses one verified standalone uv executable outside the Python environment' {
        Test-Path -LiteralPath $script:PackageUv -PathType Leaf | Should -BeTrue

        $version = (& $script:PackageUv --version | Out-String).Trim()
        $LASTEXITCODE | Should -Be 0
        $version | Should -Match ("^uv $([regex]::Escape($script:Pin.version))\s")
    }

    It 'keeps the lock, environment, and compatibility export mechanically current' {
        $priorCache = [Environment]::GetEnvironmentVariable('UV_CACHE_DIR', 'Process')
        try {
            $env:UV_CACHE_DIR = Join-Path $TestDrive 'uv-cache'
            & $script:PackageUv lock --project $script:RepositoryRoot --check --offline `
                2> (Join-Path $TestDrive 'lock.stderr') | Out-Null
            $LASTEXITCODE | Should -Be 0
            & $script:PackageUv sync --project $script:RepositoryRoot --check --offline `
                2> (Join-Path $TestDrive 'sync.stderr') | Out-Null
            $LASTEXITCODE | Should -Be 0

            $generated = Join-Path $TestDrive 'requirements.txt'
            & $script:PackageUv export --project $script:RepositoryRoot --locked --no-dev `
                --no-emit-project --no-hashes --format requirements.txt --output-file $generated `
                2> (Join-Path $TestDrive 'export.stderr') | Out-Null
            $LASTEXITCODE | Should -Be 0
            @(Get-Content -LiteralPath $generated | Select-Object -Skip 2) |
                Should -Be @(
                    Get-Content -LiteralPath (
                        Join-Path $script:RepositoryRoot 'requirements.txt') |
                    Select-Object -Skip 2)
        }
        finally {
            [Environment]::SetEnvironmentVariable('UV_CACHE_DIR', $priorCache, 'Process')
        }
    }

    It 'generates merged registrations deterministically without an ambient executable' {
        $mcpPath = Join-Path $TestDrive '.mcp.json'
        $codexPath = Join-Path $TestDrive 'config.toml'
        [System.IO.File]::WriteAllText(
            $mcpPath,
            '{"mcpServers":{"sibling":{"command":"sibling","args":[]}}}',
            [System.Text.UTF8Encoding]::new($false))
        [System.IO.File]::WriteAllText(
            $codexPath,
            "sandbox_mode = `"danger-full-access`"`n`n[mcp_servers.sibling]`n" +
            "command = `"sibling`"`nargs = [`"-m`", `"sibling`"]`n",
            [System.Text.UTF8Encoding]::new($false))

        $generator = Join-Path $script:RecipeRoot 'write-mcp-registration.ps1'
        & $generator -RepositoryRoot $script:RepositoryRoot -McpJsonPath $mcpPath `
            -CodexConfigPath $codexPath | Out-Null
        $LASTEXITCODE | Should -Be 0

        $document = Get-Content -LiteralPath $mcpPath -Raw | ConvertFrom-Json -AsHashtable
        $document.mcpServers.ContainsKey('sibling') | Should -BeTrue
        $registration = $document.mcpServers['scientiae-procurement']
        $registration.command | Should -BeExactly './packages/uv/uv.exe'
        @($registration.args) | Should -Be @(
            'run', '--project', '.', '--locked', '--no-sync',
            '--no-dev', '--offline', 'scientiae-procurement')
        $registration.env.CODEX_SCIENTIAE_ROOT | Should -BeExactly '.'
        $registration.env.UV_PROJECT_ENVIRONMENT | Should -BeExactly './.venv'
        $registration.env.UV_PYTHON_INSTALL_DIR | Should -BeExactly './packages/python'
        $registration.env.UV_CACHE_DIR | Should -BeExactly './artifacts/uv/cache'
        $registration.env.TEMP | Should -BeExactly './artifacts/procurement-mcp/temp'
        $registration.env.PYTHONPATH | Should -BeExactly ''

        $toml = Get-Content -LiteralPath $codexPath -Raw
        $toml | Should -Match '(?m)^\[mcp_servers\.sibling\]$'
        $toml | Should -Match '(?m)^\[mcp_servers\.scientiae-procurement\]$'
        $toml | Should -Match ([regex]::Escape('scientiae-procurement'))
        $toml | Should -Match ([regex]::Escape('command = "./packages/uv/uv.exe"'))
        $toml | Should -Not -Match ([regex]::Escape($script:RepositoryRoot))

        $jsonFirst = [System.IO.File]::ReadAllBytes($mcpPath)
        $tomlFirst = [System.IO.File]::ReadAllBytes($codexPath)
        & $generator -RepositoryRoot $script:RepositoryRoot -McpJsonPath $mcpPath `
            -CodexConfigPath $codexPath | Out-Null
        $LASTEXITCODE | Should -Be 0
        [System.IO.File]::ReadAllBytes($mcpPath) | Should -Be $jsonFirst
        [System.IO.File]::ReadAllBytes($codexPath) | Should -Be $tomlFirst
    }

    It 'keeps the committed repository registrations on the locked runtime shape' {
        $document = Get-Content -LiteralPath (
            Join-Path $script:RepositoryRoot '.mcp.json') -Raw |
            ConvertFrom-Json -AsHashtable
        $registration = $document.mcpServers['scientiae-procurement']
        $registration.command | Should -BeExactly './packages/uv/uv.exe'
        @($registration.args) | Should -Be @(
            'run', '--project', '.', '--locked', '--no-sync',
            '--no-dev', '--offline', 'scientiae-procurement')
        $registration.env.CODEX_SCIENTIAE_ROOT | Should -BeExactly '.'
        $registration.env.UV_PROJECT_ENVIRONMENT | Should -BeExactly './.venv'
    }
}
