#requires -Version 7.0
<#
  src/audits/md-toc.ps1 — heading anchors + the `## Contents` block, as format-agnostic markdown
  primitives (pure text in/text out; no file I/O here).

  THE one slug engine: finalize (chunk-stream emission), md-repair (post-hoc regeneration), and
  latex-ingest (born-complete deliverable) all link through Get-MdAnchor, so an anchor written by
  any lane matches a TOC regenerated by any other. Untangles the TOC concern that had drifted
  across finalize/publish/md-repair (issues/reboot/gemini-toc-generation-legacy-code.md).

  Conventions carried: GitHub-style slugs; hierarchical indentation at 2 spaces PER heading level
  below H2 (H2 flush, H3 one indent, ...); the block sits before the first body H2.
#>

# GitHub-style heading slug (was finalize.ps1 ConvertTo-Anchor / md-repair.ps1's local copy — the
# empty-slug fallback and edge Trim are finalize's, now everyone's).
function Get-MdAnchor([string]$h) {
    $a = (($h.ToLowerInvariant() -replace '[^\w\s-]', '') -replace '\s+', '-').Trim('-')
    if ($a -eq '') { return "section-$($h.GetHashCode().ToString('x8'))" }
    return $a
}

# Fence-aware H2+ heading scan over markdown TEXT -> { level; text } in reading order, the
# `## Contents` heading itself excluded. Fenced code keeps its own `#` lines out of the TOC.
function Get-MdContentsEntries([string]$Markdown) {
    $entries = [System.Collections.Generic.List[object]]::new()
    $inFence = $false
    foreach ($ln in ($Markdown -split "`n")) {
        if ($ln -match '^```') { $inFence = -not $inFence; continue }
        if ($inFence) { continue }
        if ($ln -match '^(#{2,6})\s+(.*\S)\s*$') {
            $text = $matches[2]
            if ($text -match '^(?i)contents$') { continue }
            $entries.Add([pscustomobject]@{ level = $matches[1].Length; text = $text })
        }
    }
    return ,$entries
}

# Build the block from entries. Indentation is hierarchical: 2 spaces per level below H2
# (the corpus convention md-repair's Update-MdContents also emits). $null when there is nothing
# to list — a TOC over no headings is noise, and callers treat $null as "leave the document be".
function New-MdContentsBlock($Entries) {
    if (-not $Entries -or @($Entries).Count -eq 0) { return $null }
    $toc = foreach ($e in $Entries) { ('  ' * ([Math]::Max(0, [int]$e.level - 2))) + "- [$($e.text)](#$(Get-MdAnchor $e.text))" }
    return "## Contents`n`n" + ($toc -join "`n") + "`n"
}

# Insert or refresh the block IN TEXT. An existing `## Contents` section (heading through the next
# H2, fence-aware) is replaced in place; otherwise the block lands immediately before the first
# body H2. No H2 headings -> unchanged. Idempotent: Set(Set(x)) == Set(x).
function Set-MdContentsBlock([string]$Markdown) {
    if ([string]::IsNullOrWhiteSpace($Markdown)) { return $Markdown }
    $entries = Get-MdContentsEntries $Markdown
    if ($entries.Count -eq 0) { return $Markdown }
    $blockLines = [string[]](@((New-MdContentsBlock $entries).TrimEnd() -split "`n") + @(''))

    $lines = [System.Collections.Generic.List[string]]::new([string[]]($Markdown -split "`n"))
    $inFence = $false; $start = -1; $end = -1; $firstH2 = -1
    for ($i = 0; $i -lt $lines.Count; $i++) {
        $ln = $lines[$i]
        if ($ln -match '^```') { $inFence = -not $inFence; continue }
        if ($inFence) { continue }
        if ($ln -match '^##\s+Contents\s*$') { if ($start -lt 0) { $start = $i }; continue }
        if ($ln -match '^##\s') {
            if ($start -ge 0 -and $end -lt 0) { $end = $i }
            if ($firstH2 -lt 0) { $firstH2 = $i }
        }
    }
    if ($start -ge 0) {
        $stop = if ($end -ge 0) { $end } else { $lines.Count }
        $lines.RemoveRange($start, $stop - $start)
        $lines.InsertRange($start, $blockLines)
    }
    elseif ($firstH2 -ge 0) {
        $lines.InsertRange($firstH2, $blockLines)
    }
    else { return $Markdown }   # H2s exist per the entry scan but none located: fence imbalance — do no harm
    return ($lines -join "`n")
}
